from __future__ import annotations

from typing import Protocol

from esp_drone_cli.core.protocol.messages import Frame


class Transport(Protocol):
    def send(self, data: bytes) -> None: ...
    def send_message(self, msg_type: int, payload: bytes = b"", flags: int = 0, seq: int = 0) -> None: ...
    def recv_frame(self, timeout: float) -> Frame: ...
    def close(self) -> None: ...
